#aws_cloudfront_distribution.s3_distribution.id
#aws_cloudfront_distribution.s3_distribution.arn
#aws_cloudfront_distribution.s3_distribution.status
#aws_cloudfront_origin_access_identity.origin_access_identity.id
#aws_cloudfront_origin_access_identity.origin_access_identity.etag
#aws_cloudfront_origin_access_identity.origin_access_identity.cloudfront_access_identity_path