#!/bin/bash
SERVER=$1
PLUGIN=$2
if [ -z "${SRT_REPO}" ]; then
  echo "SRT_REPO ver is not configured, using defaults."
  export SRT_REPO="${HOME}/repos/solidrust.net"
fi
echo "Using repo from: ${SRT_REPO} ."
echo "Checking for SERVER_KEYS in: ${SERVER_KEYS} ."
if [ -z "${SERVER_KEYS}" ]; then
  export SERVER_KEYS="/c/Users/shaun/repos"
  echo "No SERVER_KEYS var defined, using default of ${SERVER_KEYS} ."
else
  echo "SERVER_KEYS successfully located in: ${SERVER_KEYS} ."
fi

function usage_helper() {
  echo ""
  echo "Usage: pull_oxide_config <server> <plugin_name|all>"
  echo ""
}

case ${SERVER} in
demo)
  SCP_CMD="scp -i ${SERVER_KEYS}/solidrust-us-east-1pem.pem admin@${SERVER}.solidrust.net"
  SSH_CMD="ssh -i ${SERVER_KEYS}/solidrust-us-east-1pem.pem -tq admin@${SERVER}.solidrust.net"
  ;;
drifter)
  SCP_CMD="scp shaun@${SERVER}"
  SSH_CMD="ssh tq shaun@${SERVER}"
  ;;
nine)
  SCP_CMD="scp -i ${SERVER_KEYS}/us-west-2-solidrust.pem admin@${SERVER}.solidrust.net"
  SSH_CMD="ssh -i ${SERVER_KEYS}/us-west-2-solidrust.pem -tq admin@${SERVER}.solidrust.net"
  ;;
eleven)
  SCP_CMD="scp shaun@${SERVER}"
  SSH_CMD="ssh -tq shaun@${SERVER}"
  ;;
*)
  echo "pull_config: Invalid server selection"
  echo ""
  echo "Currently supported servers: nine, demo"
  usage_helper
  exit 1
  ;;
esac

if [ -z "${PLUGIN}" ]; then
  echo "pull_config: no plugin selection detected"
  echo ""
  echo "Please specify a plugin to pull from, such as 'AutoDoors'"
  usage_helper
  exit 1
else
  case ${PLUGIN} in
  all)
    echo "do it for Dale"
    ${SSH_CMD} "cd /game/oxide/plugins; ls -1 *.cs | rev | cut -c4- | rev > /tmp/solidrust_plugins.list"
    ${SCP_CMD}:/tmp/solidrust_plugins.list "${SRT_REPO}/servers/${SERVER}/"
    for plugin in $(cat "${SRT_REPO}/servers/${SERVER}/solidrust_plugins.list"); do
      echo "Doin the $plugin plugin"
      ${SCP_CMD}:/game/oxide/config/${plugin}.json "${SRT_REPO}/defaults/oxide/config/"
    done
    ;;
  *)
    echo "Configured destination: ${SRT_REPO}/defaults/oxide/config/"
    echo "Pulling ${PLUGIN} config from ${SERVER}"
    ${SCP_CMD}:/game/oxide/config/${PLUGIN}.json "${SRT_REPO}/defaults/oxide/config/"
    ;;
  esac
fi
