#!/bin/bash
SERVER=$1
PLUGIN=$2
REPO_DIR="/c/Users/shaun/repos/solidrust.net/defaults"
SERVER_KEYS="/c/Users/shaun/repos"

case $SERVER in

  nine)
    SCP_CMD="scp -i ${SERVER_KEYS}/us-west-2-solidrust.pem admin@nine.solidrust.net"
    ;;

  *)
    echo "pull_data: Invalid server selection"
    echo ""
    echo "Currently supported server(s): nine"
    echo ""
    echo "Usage: pull_data <server> <plugin>"
    echo ""
    ;;
esac

echo "Pulling ${PLUGIN} languages from ${SERVER}"
$SCP_CMD:/game/oxide/lang/en/${PLUGIN}.json "${REPO_DIR}/oxide/lang/en/"