#!/bin/bash
SERVER=$1
PLUGIN=$2
if [ -z "${SRT_REPO}" ]; then
  echo "SRT_REPO ver is not configured, using defaults."
  export SRT_REPO="${HOME}/repos/solidrust.net"
fi
echo "Using repo from: ${SRT_REPO} ."
echo "Checking for SERVER_KEYS in: ${SERVER_KEYS} ."
if [ -z "${SERVER_KEYS}" ]; then
  export SERVER_KEYS="/c/Users/shaun/repos"
  echo "No SERVER_KEYS var defined, using default of ${SERVER_KEYS} ."
else
  echo "SERVER_KEYS successfully located in: ${SERVER_KEYS} ."
fi

case $SERVER in
nine)
  SCP_CMD="scp -i ${SERVER_KEYS}/us-west-2-solidrust.pem -r admin@nine.solidrust.net"
  ;;

*)
  echo "pull_data: Invalid server selection"
  echo ""
  echo "Currently supported server(s): nine"
  echo ""
  echo "Usage: pull_data <server> <plugin>"
  echo ""
  ;;
esac

case $PLUGIN in
kits|Kits)
  echo "Pulling Kits data from ${SERVER}"
  $SCP_CMD:/game/oxide/data/Kits/Kits.json "${SRT_REPO}/defaults/oxide/data/Kits/"
  ;;
copypaste|CopyPaste)
  echo "Pulling CopyPaste data from ${SERVER}"
  $SCP_CMD:/game/oxide/data/copypaste/*.json "${SRT_REPO}/defaults/oxide/data/copypaste/"
  ;;
security|Security|guardian|Guardian|serverarmour|ServerArmour)
  echo "Pulling Security data from ${SERVER}"
  $SCP_CMD:/game/oxide/data/Guardian/* "${SRT_REPO}/defaults/oxide/data/Guardian/"
  $SCP_CMD:/game/oxide/data/ServerArmour/* "${SRT_REPO}/defaults/oxide/data/ServerArmour/"
  $SCP_CMD:/game/oxide/data/Arkan/* "${SRT_REPO}/defaults/oxide/data/Arkan/"
  ;;
bank|Bank|backpacks|Backpacks)
  echo "Pulling PerformanceMonitor data from ${SERVER}"
  $SCP_CMD:/game/oxide/data/banks/* "${SRT_REPO}/defaults/oxide/data/banks/"
  $SCP_CMD:/game/oxide/data/Backpacks/* "${SRT_REPO}/defaults/oxide/data/Backpacks/"
  ;;
craftsman|Craftsman)
  echo "/game/oxide/data/PlayerCrafting*"
  $SCP_CMD:/game/oxide/data/PlayerCrafting* "${SRT_REPO}/defaults/oxide/data/"
  ;;
raidablebases|RaidableBases)
  echo "/game/oxide/data/RaidableBases"
  $SCP_CMD:/game/oxide/data/RaidableBases "${SRT_REPO}/defaults/oxide/data/"
  ;;
betterloot|BetterLoot)
  echo "/game/oxide/data/BetterLoot"
  $SCP_CMD:/game/oxide/data/BetterLoot "${SRT_REPO}/defaults/oxide/data/"
  ;;
*)
  echo "pull_data: Invalid plugin selection"
  echo ""
  echo "Currently supported plugins: kits, copypaste"
  echo ""
  echo "Usage: pull_data <server> <plugin>"
  echo ""
  ;;
esac
