#!/bin/bash
SERVER=$1
PLUGIN=$2
REPO_DIR="/c/Users/shaun/repos/solidrust.net/defaults"
SERVER_KEYS="/c/Users/shaun/repos"

case $SERVER in
nine)
  SCP_CMD="scp -i ${SERVER_KEYS}/us-west-2-solidrust.pem -r admin@nine.solidrust.net"
  ;;

*)
  echo "pull_data: Invalid server selection"
  echo ""
  echo "Currently supported server(s): nine"
  echo ""
  echo "Usage: pull_data <server> <plugin>"
  echo ""
  ;;
esac

case $PLUGIN in
kits|Kits)
  echo "Pulling Kits data from ${SERVER}"
  $SCP_CMD:/game/oxide/data/Kits/Kits.json "${REPO_DIR}/oxide/data/Kits/"
  ;;
shop|Shop)
  echo "Pulling Shop data from ${SERVER}"
  $SCP_CMD:/game/oxide/data/Shop.json "${REPO_DIR}/oxide/data/"
  ;;
copypaste|CopyPaste)
  echo "Pulling CopyPaste data from ${SERVER}"
  $SCP_CMD:/game/oxide/data/copypaste/*.json "${REPO_DIR}/oxide/data/copypaste/"
  ;;
security|Security|guardian|Guardian|serverarmour|ServerArmour)
  echo "Pulling Security data from ${SERVER}"
  $SCP_CMD:/game/oxide/data/Guardian/* "${REPO_DIR}/oxide/data/Guardian/"
  $SCP_CMD:/game/oxide/data/ServerArmour/* "${REPO_DIR}/oxide/data/ServerArmour/"
  $SCP_CMD:/game/oxide/data/Arkan/* "${REPO_DIR}/oxide/data/Arkan/"
  ;;
performance|PerformanceMonitor)
  echo "Pulling PerformanceMonitor data from ${SERVER}"
  $SCP_CMD:/game/oxide/data/PerformanceMonitor/* "${REPO_DIR}/oxide/data/PerformanceMonitor/"
  ;;
bank|Bank|backpacks|Backpacks)
  echo "Pulling PerformanceMonitor data from ${SERVER}"
  $SCP_CMD:/game/oxide/data/banks/* "${REPO_DIR}/oxide/data/banks/"
  $SCP_CMD:/game/oxide/data/Backpacks/* "${REPO_DIR}/oxide/data/Backpacks/"
  ;;
craftsman|Craftsman)
  echo "/game/oxide/data/PlayerCrafting*"
  $SCP_CMD:/game/oxide/data/PlayerCrafting* "${REPO_DIR}/oxide/data/"
  ;;
*)
  echo "pull_data: Invalid plugin selection"
  echo ""
  echo "Currently supported plugins: kits, copypaste"
  echo ""
  echo "Usage: pull_data <server> <plugin>"
  echo ""
  ;;
esac
