#!/bin/bash
## mysqldump -u [username] -p [database] > dump.sql
## mysql -u [username] -p [database] < [dump_file].sql
SERVER=$1
DATABASE=$2
REPO_DIR="/c/Users/shaun/repos/solidrust.net"
SERVER_KEYS="/c/Users/shaun/repos/us-west-2-solidrust.pem"
LOG_DATE=$(date +"%Y_%m_%d_%I_%M_%S_%p")
ALL_DATABASES=(PermissionGroupSync
  RustPlayers
  mysql
  oxide
  rustplayers
  solidrust_demo
  solidrust_lcy
  solidrust_players
  srt_web_auth)

if [ -z "${SERVER}" ]; then
  echo ""
  echo ""
  echo "pull_database: Invalid server selection"
  echo ""
  echo "suggested server(s): data-dev"
  echo ""
  echo "Usage: push_database <server> <database_name|all>"
  echo ""
  exit 1
else
  SSH_CMD="ssh -i ${SERVER_KEYS} -tq admin@${SERVER}.solidrust.net" #TODO implement something for regional ssh keys
  SCP_DEST="admin@${SERVER}.solidrust.net"
fi

if [ -z "${DATABASE}" ]; then
  echo ""
  echo ""
  echo "pull_database: Invalid database selection"
  echo ""
  echo "Suggested databases:"
  echo "  - solidrust_lcy"
  echo ""
  echo "Usage: push_database <server> <database_name|all>"
  echo ""
  exit 1
else
  case ${DATABASE} in
  all | full)
    for database in ${ALL_DATABASES[@]}; do
      if [ -z "${REPO_DIR}/servers/${SERVER}/${database}.sql" ]; then
        echo "Unable to load: ${REPO_DIR}/servers/${SERVER}/${database}.sql"
      else
        echo "=>Pushing ${database} database to ${SERVER}.solidrust.net"
        scp -i ${SERVER_KEYS} "${REPO_DIR}/servers/${SERVER}/${database}.sql" "${SCP_DEST}:/tmp/"
        echo "saved to: ${SCP_DEST}:/tmp/${database}.sql"
        ${SSH_CMD} "sudo mysql -u root -e \"DROP DATABASE IF EXISTS ${database}\""
        ${SSH_CMD} "sudo mysqladmin -u root create ${database}"
        ${SSH_CMD} "sudo mysql -u root ${database} < /tmp/${database}.sql"
        ${SSH_CMD} "sudo mysql -u root -e \"GRANT ALL PRIVILEGES ON *.* TO 'srt_sl_lcy'@'%' IDENTIFIED BY 'lcy_402' WITH GRANT OPTION; FLUSH PRIVILEGES;\""
      fi
    done
    ;;
  *)
    echo "fuck you"
    ;;
  esac
fi
