#!/bin/bash
CURRENT_DIR=$(pwd)
if [ -z "${SRT_REPO}" ]; then
  echo "SRT_REPO var is not configured, using defaults."
  export SRT_REPO="${HOME}/repos/solidrust.net"
fi
echo "Using repo from: ${SRT_REPO} ."
S3_REPO="s3://solidrust.net-repository"
echo "Creating SRT Build marker"
cd ${SRT_REPO}
git fetch --tags
git rev-parse --short HEAD | tee build.txt
git tag | tac | tee -a build.txt
cd ${CURRENT_DIR}
export S3_COMMAND="sync --delete --exclude *DS_Store --exclude *.pem"
echo "Pushing SRT Build marker"
aws s3 cp ${SRT_REPO}/build.txt ${S3_REPO}/
echo "Pushing SRT global default server configs"
aws s3 ${S3_COMMAND} ${SRT_REPO}/defaults/ ${S3_REPO}/defaults/
echo "Pushing SRT customized server configs"
aws s3 ${S3_COMMAND} ${SRT_REPO}/servers/ ${S3_REPO}/servers/
echo "Pushing SRT Web"
aws s3 ${S3_COMMAND} ${SRT_REPO}/web/ ${S3_REPO}/web/
echo "Pushing SRT Services"
aws s3 ${S3_COMMAND} ${SRT_REPO}/apps/ ${S3_REPO}/apps/
echo "Done!"